### PR TITLE
#167919131 Code clean up - remove unwanted packages, folders and files

### PR DESCRIPTION
**Pull request by richienabuk**
#### What does this PR do?
Remove irrelevant packages, folders, and files

#### Any background context you want to provide?
- The project contained MongoDB setup whereas project requirement specified Postgres
- The project also had configuration files not needed and un-decided for Barefoot nomad project by cyclops team.

#### What are the relevant pivotal tracker stories?
[#167919131](https://www.pivotaltracker.com/n/projects/2381984/stories/167919131)

### CODE REVIEW

**Review by dieudonneAwa — APPROVED** [review]
It looks cool. I think this is good to go.

**Review by Wokoro — APPROVED** [review]

**Comment by Abobos** [comment]
Your PR "description of task to be completed" Is displaying  "Setup Postures DB and Sequelize"

**Review by Abobos — APPROVED** [review]

**Comment by Wokoro** [comment]
You should also add link to the story ID.  Currently the story ID is not linked.

**Review by Kingobaino — APPROVED** [review]

**Comment by richienabuk** [comment]
> You should also add link to the story ID. Currently the story ID is not linked.

Done!
Thanks

**Comment by richienabuk** [comment]
> Your PR "description of task to be completed" Is displaying "Setup Postures DB and Sequelize"

I've removed that.

Thanks

**Review by biolabalo — APPROVED** [review]

**Pull request merged**
